public_key: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

poll_interval: 0.1

defaults:
  - _self_
  - hydra: defaults
  - provider: httpprovider
  - contract: data
  - ipfs: ipfs_config
  - db: sqlite
  - model: sdxl-turbo